name: postman
on: 
 schedule:
    - cron: '0 * * * *' # At 00:00 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
  steps:
  - name: Check out Git repositor
    uses: actions/checkout@v1
  - name: Set up Node.js
    uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}
      registry-url: https://registry.npmjs.org/
  
  - name: Install dependencies
    run: npm install
  - name: Install newman
    run: npm install -g newman

  - name: Run the API and Postman's tests
    run: | 
      newman run "Reqres.in.postman_collection.json"
    
